#!/bin/bash
printf '%o' $(( $(echo $WATER|tr 'water' '01234'|awk '{n=0;l=split($0,a,"");for(i=1;i<=l;i++)n=n*5+a[i];print n}') + $(echo $STIR|tr 'stir.' '01234'|awk '{n=0;l=split($0,a,"");for(i=1;i<=l;i++)n=n*5+a[i];print n}') )) | tr '01234567' 'bestchol'
